# Generated by Django 4.2.4 on 2023-08-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_new', '0002_touristplace_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristplace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
