# Generated by Django 4.2.4 on 2023-08-16 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls_new', '0005_cart_cartitem_delete_carbooking_cart_cars_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cars',
            field=models.ManyToManyField(through='polls_new.CartItem', to='polls_new.car'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_new.car'),
        ),
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_new.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
