# Generated by Django 4.2.4 on 2023-08-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_new', '0006_alter_cart_cars_alter_cartitem_car_carbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbooking',
            name='car',
        ),
        migrations.RemoveField(
            model_name='carbooking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cars',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='car',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='CarBooking',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
