# Generated by Django 4.2.4 on 2023-08-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_new', '0008_carbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
