# Generated by Django 4.2.4 on 2023-08-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_new', '0009_carbooking_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplace',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='CarBooking',
        ),
    ]
