# Generated by Django 4.2.4 on 2023-08-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_new', '0012_remove_touristplace_bookings_delete_carbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplace',
            name='visibility',
            field=models.CharField(choices=[('user', 'For User Only'), ('all', 'For All Users')], default='user', max_length=10),
        ),
    ]
